version: '3'

services:
  magick-rust:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # for debug
#    volumes:
#      - ./../../magick-rust:/usr/src/magick-rust
    stdin_open: true
    tty: true
